"""Generate a project-local Codex config; never edit the user's global config."""
import argparse
import json
from pathlib import Path
import sys


def configure(root, python, with_docs=False):
    root=Path(root).resolve()
    quote=lambda p: json.dumps(str(p).replace('\\','/'))
    content='\n'.join([
        '# Generated by solidworks-ai-workflow. Project-local; contains no secrets.',
        '[mcp_servers.sw_workflow]',
        'command = '+quote(python),
        'args = ["-X", "utf8", "-B", "-m", "sw_workflow.mcp_server"]',
        'cwd = '+quote(root),
        'startup_timeout_sec = 30',
        'tool_timeout_sec = 300',
        '[mcp_servers.sw_workflow.env]',
        'PYTHONUTF8 = "1"',
        'SW_WORKFLOW_OUTPUT = '+quote(root/'artifacts'),
        '',
    ])
    if with_docs:
        content+='\n[mcp_servers.swapi_pilot]\nurl = "https://swapi-pilot.com/mcp"\n'
    target=root/'.codex'/'config.toml'
    skill=root/'.agents'/'skills'/'solidworks-workflow'/'SKILL.md'
    source=root/'skills'/'solidworks-workflow'/'SKILL.md'
    for path,expected in ((target,content),(skill,source.read_text(encoding='utf-8'))):
        if path.exists() and path.read_text(encoding='utf-8')!=expected:
            raise RuntimeError(f'Existing local file differs; preserve and merge it manually: {path}')
    target.parent.mkdir(parents=True,exist_ok=True)
    skill.parent.mkdir(parents=True,exist_ok=True)
    target.write_text(content,encoding='utf-8')
    skill.write_text(source.read_text(encoding='utf-8'),encoding='utf-8')
    return target


if __name__=='__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('--with-docs',action='store_true')
    args=parser.parse_args()
    print(configure(Path(__file__).resolve().parent.parent,sys.executable,args.with_docs))
